#include<stdio.h>
#include<conio.h>
void main()
{
int a;
char y;
char d;
signed int b;
signed short int c;
unsigned int e;
float f;
double d1;
float f1;
signed int s1;
long float f2;
printf("int=%d,char=%c,charcap=%c,signed int=%hi,unsignedshort int=%hu,unsigned float=%lf
,float=%f,sihned int=%i,float=%Lf");
scanf("%d,%c,%c",%hi,%hu,%f,%i,%Lf,&a,&y,&d,&b,&c,&e,&f,&d1,&f1,
&s1,&f2);
getch();

}
